## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vswitch_module.html#ansible-collections-community-vmware-vmware-vswitch-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_portgroup_module.html 

---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "200.200.200.251"
    vcenter_username: "administrator@vsphere.kh"
    vcenter_password: "VMware1!"
##    esxi_hostname: "200.200.200.250"
    esxi_username: "root"
    esxi_password: "VMware1!"
##    student_ID: "S00"

  vars_prompt:
    - name: student_ID
      prompt: What is your student ID (ex:S00)?
      private: no

    - name: esxi_hostname
      prompt: What is your esxi_hostname (ex:200.200.200.250)?
      private: no

  tasks: 
    - name: Create Lab Standard Switch
      community.vmware.vmware_vswitch:
          hostname: '{{ esxi_hostname }}'
          username: '{{ esxi_username }}'
          password: '{{ esxi_password }}'
          validate_certs: no
          switch: '{{ student_ID }}'
      delegate_to: localhost


    - name: Waiting 10 seconds for completing switch
      wait_for:
        timeout: 10
      delegate_to: localhost


    - name: Adding Trunk Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Trunk' }}"
          vlan_id: 4095
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A Management Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Mgmt' }}"
          vlan_id: 101
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A Storage Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Storage' }}"
          vlan_id: 102
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A vMotion Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-vMotion' }}"
          vlan_id: 103
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost
