## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vswitch_module.html#ansible-collections-community-vmware-vmware-vswitch-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_portgroup_module.html 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vcenter_folder_module.html#ansible-collections-community-vmware-vcenter-folder-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_deploy_ovf_module.html#ansible-collections-community-vmware-vmware-deploy-ovf-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html#ansible-collections-community-vmware-vmware-vm-shell-module
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#ansible-collections-community-vmware-vmware-guest-module


---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "200.200.200.251"
    vcenter_username: "administrator@vsphere.kh"
    vcenter_password: "VMware1!"
    datacenter_name: "vSAN Datacenter"
    esxi_hostname: "200.200.200.247"
    esxi_username: "root"
    esxi_password: "VMware1!"
##    student_ID: "S00"
    folder_prefix: "Students/"
    full_folder_prefix: "vSAN Datacenter/vm/Students/"
    public_net: "VM Network"
    private_net: "{{ student_ID + '-Trunk' }}"
    template_name: "Temp-Win2019"
    snapshot_src_name: "20220412"    

  vars_prompt:
    - name: student_ID
      prompt: What is your student ID (ex:S00)?
      private: no

  tasks: 
    - name: Create Lab Standard Switch
      community.vmware.vmware_vswitch:
          hostname: '{{ esxi_hostname }}'
          username: '{{ esxi_username }}'
          password: '{{ esxi_password }}'
          validate_certs: no
          switch: '{{ student_ID }}'
      delegate_to: localhost


    - name: Waiting 10 seconds for completing switch
      wait_for:
        timeout: 10
      delegate_to: localhost


    - name: Adding Trunk Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Trunk' }}"
          vlan_id: 4095
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A Management Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Mgmt' }}"
          vlan_id: 101
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A Storage Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Storage' }}"
          vlan_id: 102
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A vMotion Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-vMotion' }}"
          vlan_id: 103
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost
      
      

## router
    - name: Create a sub folder under VM folder on given datacenter
      community.vmware.vcenter_folder:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: no
          datacenter: '{{ datacenter_name }}'
          folder_type: vm
          folder_name: '{{ student_ID }}'
          parent_folder: '{{ folder_prefix }}'
          state: present
      register: sub_folder_creation_result
      delegate_to: localhost


    - name: Deploy VyOS ova
      community.vmware.vmware_deploy_ovf:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          datacenter: '{{ datacenter_name }}'
          folder: "{{ full_folder_prefix + student_ID }}"
          esxi_hostname: '{{ esxi_hostname }}'
          datastore: 'vsanDatastore'
          name: "{{ student_ID + '-Router' }}"
          networks: { 'DPG-172.0.10.x': "{{ public_net }}", 'DPG-172.0.20.x': "{{ private_net }}" }
          power_on: no
          ovf: /mnt/c/temp-vyos-1.4.ova    
      delegate_to: localhost


    - name: Perform vMotion of virtual machine
      community.vmware.vmware_vmotion:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_name: "{{ student_ID + '-Router' }}"
          destination_host: '{{ esxi_hostname }}'
      delegate_to: localhost


    - name: Set the state of a virtual machine to poweron
      community.vmware.vmware_guest_powerstate:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: 'false'
          folder: '{{ full_folder_prefix + student_ID }}'
          name: "{{ student_ID + '-Router' }}"
          state: powered-on
      delegate_to: localhost


    - name: Waiting 60 seconds for completing bootup
      wait_for:
        timeout: 60
      delegate_to: localhost


    - name: VyOS Router Configuration
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          datacenter: '{{ datacenter_name }}'
          folder: "{{ full_folder_prefix + student_ID }}"
          vm_id: "{{ student_ID + '-Router' }}"
          vm_id_type: vm_name
          vm_username: 'vyos'
          vm_password: 'vyos'
          vm_shell: /bin/vbash
          vm_shell_cwd: "/tmp"
          vm_shell_args: |-
            -c "source /opt/vyatta/etc/functions/script-template
            configure
            set system login user admin full-name Admin_User
            set system login user admin authentication plaintext-password VMware1!
            set service ssh port 22
            
            set interfaces ethernet eth0 address dhcp
            set interfaces ethernet eth0 description Outside
            set protocols static route 0.0.0.0/0 next-hop 200.200.200.254
            
            set system name-server 200.200.200.245
            set system ntp server kr.pool.ntp.org
            
            set interfaces ethernet eth1 vif 101 description 'VLAN 101 - Site A Management'
            set interfaces ethernet eth1 vif 101 address 10.10.1.1/24
            set interfaces ethernet eth1 vif 102 description 'VLAN 102 - Site A Storage'
            set interfaces ethernet eth1 vif 102 address 10.10.2.1/24
            
            set nat source rule 100 outbound-interface eth0
            set nat source rule 100 source address 10.10.1.0/24
            set nat source rule 100 translation address masquerade
            
            commit
            save"
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout      
      
      
## DC
    - name: Deploy Domain Controller VM from Template
      community.vmware.vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          name: "{{ student_ID + '-DC' }}"
          state: "poweredon"
          datacenter: '{{ datacenter_name }}'
          folder: "{{ full_folder_prefix + student_ID }}"
          esxi_hostname: '{{ esxi_hostname }}'
          datastore: "{{ datastore_name }}"
          template: "{{ template_name }}"
          linked_clone: True
          snapshot_src: "{{ snapshot_src_name }}"
          networks:
    - name: "{{ student_ID + '-Mgmt' }}"
          connected: True
          start_connected: True
          ip: 10.10.1.2
          netmask: 255.255.255.0
          gateway: 10.10.1.1
          dns_servers: 200.200.200.245
          type: static
      customization:
        password: VMware1!
          wait_for_customization: yes
          wait_for_customization_timeout: 900
      delegate_to: localhost

    - name: shutdown VM to change network connection
      community.vmware.vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          name: "{{ student_ID + '-DC' }}"
          state: "shutdownguest"
          state_change_timeout: 60
      delegate_to: localhost

    - name: Poweron DC VM
      community.vmware.vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          name: "{{ student_ID + '-DC' }}"
          state: "poweredon"
          state_change_timeout: 60
      delegate_to: localhost      
    
    
 ## AD-DS
    - name: Install_WindowsFeatures_AD-DS
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_id: "{{ student_ID + '-DC' }}"
          vm_id_type: vm_name
          vm_username: 'Administrator'
          vm_password: 'VMware1!'
          vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
          vm_shell_args: '-command "(Install-WindowsFeature -Name AD-Domain-Services -IncludeManagementTools)"'
          vm_shell_cwd: 'c:\Users\Administrator'
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout

    - name: Import_Module_ADDSDeployment
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_id: "{{ student_ID + '-DC' }}"
          vm_id_type: vm_name
          vm_username: 'Administrator'
          vm_password: 'VMware1!'
          vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
          vm_shell_args: '-command "Import-Module ADDSDeployment"'
          vm_shell_cwd: 'c:\Users\Administrator'
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout


    - name: Install_First_ADDSForest
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_id: "{{ student_ID + '-DC' }}"
          vm_id_type: vm_name
          vm_username: 'Administrator'
          vm_password: 'VMware1!'
          vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
          vm_shell_args: '-command "(Install-ADDSForest -CreateDnsDelegation:$false -DatabasePath C:\Windows\NTDS -DomainMode WinThreshold -DomainName vclass.local -DomainNetbiosName VCLASS -ForestMode WinThreshold -InstallDns:$true -LogPath C:\Windows\NTDS -NoRebootOnCompletion:$false -SysvolPath C:\Windows\SYSVOL -Force:$true -SafeModeAdministratorPassword (ConvertTo-SecureString -AsPlainText "VMware1!" -force)")"'
          vm_shell_cwd: 'c:\Users\Administrator'
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout    
